project:
  title: "Posit Documentation"
  type: posit-docs

website:
  title: "docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true



